version: '2'
services:
  mongo:
    image: mongo:3.4
    volumes:
      - mongodb-data:/data/db
  web:
    build: .
    environment:
      NODE_ENV: development
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    restart: on-failure
    ports:
      - "3000:8080"
    command: yarn dev -- -L 
    environment:
     - MONGODB_URI=mongodb://mongo:27017/test 
    links:
     - mongo 
    depends_on: 
     - mongo

volumes:
  mongodb-data:
     